swagger: "2.0"
info:
  version: "0.3.6"
  title: BetProtocol MicroService
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /api
# 

schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /withdraw/max/set :
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Set max withdraw
      operationId: setMaxWithdraw
      description: Set max withdraw Data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: withdraw
          description: Set max withdraw
          required: true
          schema:
            $ref: '#/definitions/SetMaxWithdraw'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /status/post:
    x-swagger-router-controller: ping
    post:
      tags:
      - ping
      summary: Test Ping
      operationId: pingPost
      description: Test Ping for post.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: ping
          description: Ping Object for test
          required: true
          schema:
            $ref: '#/definitions/PingPost'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /withdraw/min/set :
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Set Min withdraw
      operationId: setMinWithdraw
      description: Set Min withdraw Data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: withdraw
          description: Set Min withdraw
          required: true
          schema:
            $ref: '#/definitions/SetMinWithdraw'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /affiliate/withdraw/min/set :
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Set Affiliate Min withdraw
      operationId: setAffiliateMinWithdraw
      description: Set Affiliate Min withdraw Data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: withdraw
          description: Set Affiliate Min withdraw
          required: true
          schema:
            $ref: '#/definitions/SetAffiliateMinWithdraw'
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users/requestWithdraw: 
    x-swagger-router-controller: user
    post:
      tags:
      - user
      summary: Request for User Withdraw
      operationId: requestWithdraw
      description: Update Wallet Amount for the User
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User Information
          required: true
          schema:
            $ref: '#/definitions/UserWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/finalizeWithdraw:
    x-swagger-router-controller: user
    post:
      tags:
      - user
      summary: Request for User Finalize Withdraw
      operationId: finalizeWithdraw
      description: Request Finalize Withdraw
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User Information
          required: true
          schema:
            $ref: '#/definitions/UserFinalizeWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users/cancelWithdraw:
    x-swagger-router-controller: user
    post:
      tags:
      - user
      summary: Request for User Cancel Withdraw
      operationId: cancelWithdraw
      description: Request Cancel Withdraw
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User Information
          required: true
          schema:
            $ref: '#/definitions/UserCancelWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /app/finalizeWithdraw:
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Request for App Finalize Withdraw
      operationId: finalizeAppWithdraw
      description: Request Finalize Withdraw
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: app
          description: App Information
          required: true
          schema:
            $ref: '#/definitions/AppFinalizeWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /users/affiliate/requestWithdraw:
    x-swagger-router-controller: user
    post:
      tags:
      - user
      summary: Request for User Withdraw
      operationId: requestAffiliateWithdraw
      description: Update Wallet Amount for the User
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User Information
          required: true
          schema:
            $ref: '#/definitions/UserWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /app/requestWithdraw: 
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Request for User Withdraw
      operationId: requestAppWithdraw
      description: Update Wallet Amount for the User
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: app
          description: App Information
          required: true
          schema:
            $ref: '#/definitions/AppRequestWithdrawRequest'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /app/users/withdraws:
    x-swagger-router-controller: app
    post:
      tags:
      - app
      summary: Request for User Withdraw
      operationId: getUserWithdraws
      description: Get User Withdraws
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: app
          description: App Information
          required: true
          schema:
            $ref: '#/definitions/GetAllUsersAppWithdraws'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GeneralResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
  
# complex objects have schema definitions
definitions:
  SetMaxWithdraw :
    type: object
    required:
      - wallet_id
      - amount
      - app
    properties:
      wallet_id:
        type : string
        description: |
          Unique identifier of the wallet
      amount:
        type : number
        description: |
          Max value for withdraw
      app:
        type : string
        description: |
          ID app
  PingPost:
    type: object
    required :
      - type
    properties:
      type:
        type : string
        example: "24234g234g23g"
        minLength: 1
        description: |
          Type Auth
      app:
        type : string
        example: "24234g234g23g"
        description: |
          APP ID
  SetMinWithdraw :
    type: object
    required:
      - wallet_id
      - amount
      - app
    properties:
      wallet_id:
        type : string
        description: |
          Unique identifier of the wallet
      amount:
        type : number
        description: |
          Max value for withdraw
      app:
        type : string
        description: |
          ID app

  SetAffiliateMinWithdraw :
    type: object
    required:
      - wallet_id
      - amount
      - app
    properties:
      wallet_id:
        type : string
        description: |
          Unique identifier of the wallet
      amount:
        type : number
        description: |
          Max value for withdraw
      app:
        type : string
        description: |
          ID app

  AppRequestWithdrawRequest : 
    type: object
    required:
      - app
      - address
      - tokenAmount
      - nonce
      - currency
    properties:
      tokenAmount : 
        type : number
        example: 203
        description: |
          Amount of Tokens to be Withdraw
      nonce:
        type : number
        example: 3245
        description: |
          Use Nonce
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          App ID
      address :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
      currency :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
  UserWithdrawRequest : 
    type: object
    required:
      - app
      - user
      - address
      - tokenAmount
      - nonce
      - currency
    properties:
      tokenAmount : 
        type : number
        example: 203
        description: |
          Amount of Tokens to be Withdraw
      nonce:
        type : number
        example: 3245
        description: |
          Use Nonce
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          App ID
      user :
        type : string
        format: name
        example : "5cuedgq7e6t334t34" 
        description: |
          User ID
      address :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
      currency :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
  UserCancelWithdrawRequest :
    type: object
    required:
      - app
      - user
      - withdraw_id
      - currency
      - note
    properties:
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34"
        description: |
          App ID
      user :
        type : string
        format: name
        example : "5cuedgq7e6t334t34"
        description: |
          User ID
      withdraw_id :
        type : string
        format: name
        example: "65f76st8vdsb3181"
        description: |
            Withdraw Id
      currency :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
      note :
        type : string
        format: name
        example: "Test Test"
        description: |
          Note text
  UserFinalizeWithdrawRequest :
    type: object
    required:
      - app
      - user
      - withdraw_id
      - currency
    properties:
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          App ID
      user :
        type : string
        format: name
        example : "5cuedgq7e6t334t34" 
        description: |
          User ID
      withdraw_id :
        type : string
        format: name
        example: "65f76st8vdsb3181"
        description: |
            Withdraw Id
      currency :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
  AppFinalizeWithdrawRequest : 
    type: object
    required:
      - app
      - withdraw_id
      - currency
    properties:
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          App ID
      withdraw_id :
        type : string
        format: name
        example: "53746tcuhn324"
        description: |
          Withdraw Id
      currency :
        type : string
        format: name
        example: "0xe8rghwe8rghwe9r87ynw987eyncwre"
        description: |
          User Address
  GetAllUsersAppWithdraws : 
    type: object
    required:
      - app
    properties:
      app :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          App ID
      size :
        type : number
      user :
        type : string
        format : name
        example : "5cuedgq7e6t334t34" 
        description: |
          User Id
      offset :
        type : number
      status :
        type : string
        example : "Queue" 
  GeneralResponse : 
    type: object
    required:
      - data
      - meta            
    properties:
      data:
        type : object
        format: data
        description: |
          Unique identifier of the user, besides the ID
      meta:
        type : object
        format: meta
        description: |
          User Real Name
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string